filter unity packages by adding: -coverageOptions "generateHtmlReport;assemblyFilters:-*unity*"

diff --git a/.github/workflows/UMVC.Editor.master.yml b/.github/workflows/UMVC.Editor.master.yml
--- a/.github/workflows/UMVC.Editor.master.yml
+++ b/.github/workflows/UMVC.Editor.master.yml
@@ -10,24 +10,33 @@ on:
 
 jobs:
   test:
-    name: Test 🧪
+    name: Test UMVC.Editor 🧪
     runs-on: ubuntu-latest
     container: gableroux/unity3d:2019.3.13f1
+
     steps:
-        
       - name: Wait for build to succeed
         uses: fountainhead/action-wait-for-check@v1.0.0
         id: wait-for-build
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
-          checkName: Build
+          checkName: Build UMVC.Core 🏗️
           ref: ${{ github.sha }}
-      
+
+      - name: Is UMVC.Core failing?
+        if: ${{ steps.wait-for-build.outputs.conclusion == 'failure' }}
+        run: echo "::error There is a problem with your UMVC.Core build! Exiting!!" && exit 1
+
       - uses: actions/checkout@v2
-          
-      - name: Is UMVC.Core failing? 
-        if: ${{ steps.wait-for-build.outputs.conclusion == 'failure' }} 
-        run: ">&2 echo 'There is a problem with your UMVC.Core build!\\n Exiting!!' && exit 1"
+
+      - name: Install dependencies
+        run: apt-get update && apt-get install python-pip unzip curl -y && pip install requests
+
+      - name: Download UMVC.Core Build
+        run: python .github/workflows/scripts/downloadArtifacts.py ${{ secrets.PERSONAL_TOKEN }}
+
+      - name: Unzip and move UMVC.Core dlls
+        run: sh .github/workflows/scripts/install-umvc.editor-deps.sh
 
       - name: Decrypt the license file
         run: openssl aes-256-cbc -d -in .github/Unity_v2019.x.ulf.enc -k ${{ secrets.UNITY_LICENSE_DECRYPT_KEY }} >> .github/Unity_v2019.x.ulf
@@ -38,5 +47,13 @@ jobs:
 
       # Run tests
       - name: Run tests
-        run: xvfb-run /opt/Unity/Editor/Unity -quit -batchmode -nographics -logFile -runTests -testPlatform editmode
+        run: sh .github/workflows/scripts/run-editor-tests.sh
+
+      - name: Codecov
+        uses: codecov/codecov-action@v1.0.7
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+          file: ./CodeCoverage/UMVC-opencov/EditMode/TestCoverageResults_0000.xml
+          name: codecov-umbrella
+          fail_ci_if_error: true
 #  
