adding download of latest artifact

diff --git a/.github/workflows/UMVC.Editor.pull-request.yml b/.github/workflows/UMVC.Editor.pull-request.yml
--- a/.github/workflows/UMVC.Editor.pull-request.yml
+++ b/.github/workflows/UMVC.Editor.pull-request.yml
@@ -23,9 +23,21 @@ jobs:
           
       - name: Is UMVC.Core failing?
         if: ${{ steps.wait-for-build.outputs.conclusion == 'failure' }}
-        run: ">&2 echo 'There is a problem with your UMVC.Core build!\\n Exiting!!' && exit 1"
+        run: echo "::error There is a problem with your UMVC.Core build! Exiting!!" && exit 1
       
       - uses: actions/checkout@v2
+
+      - uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
+          
+      - name: Install python dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install requests
+        
+      - name: Download UMVC.Core Build
+        run: python .github/workflows/scripts/downloadArtifacts.py
 
       - name: Decrypt the license file
         run: openssl aes-256-cbc -d -in .github/Unity_v2019.x.ulf.enc -k ${{ secrets.UNITY_LICENSE_DECRYPT_KEY }} >> .github/Unity_v2019.x.ulf
